version: "3.3"
services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:7-alpine"
    container_name: redis-server
    ports:
      - "6379:6379"

