version: "3.3"

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://flask_user:flask_pass@db:5432/flask_db

  redis:
    image: "redis:7-alpine"
    container_name: redis-server
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_pass
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

